In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('homeprices.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [11]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [12]:
model.coef_

array([135.78767123])

In [13]:
model.intercept_

180616.43835616432

In [15]:
model.predict([[5000]])

array([859554.79452055])

In [16]:
import pickle

In [17]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)


In [19]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [20]:
mp.predict([[5000]])

array([859554.79452055])

In [28]:
 
 import joblib
 
 joblib.dump(model, 'filename.joblib')

['filename.joblib']

In [29]:
mj = joblib.load('filename.joblib')

In [30]:
mj.predict([[5000]])

array([859554.79452055])